name: ChunkHeat
version: ${project.version}
main: com.ghostchu.chunkheat.ChunkHeat
api-version: 1.13
authors: [ Ghost_chu ]
description: An simple broad spectrum monster farm limiter.
commands:
  chunkheat:
    description: chunk heat
    usage: /chunkheat
